#!/usr/bin/env python3

# Copyright (C) 2020 Andrew Trettel

import sqlite3
import sys

DEFAULT_DATABASE   = "references.db"
DEFAULT_LANGUAGE   = "eng"
DEFAULT_PDFVIEWER  = "zathura"
DEFAULT_REPOSITORY = "./"

def init( database ):
    conn = sqlite3.connect( database )
    c = conn.cursor()

    c.execute(
    """
    CREATE TABLE documents (
    citation_key TEXT PRIMARY KEY UNIQUE,
    type         TEXT NOT NULL,
    notes        TEXT DEFAULT NULL
    );
    """
    )

    c.execute(
    """
    CREATE TABLE fields (
    citation_key TEXT NOT NULL,
    type         TEXT NOT NULL,
    language     TEXT NOT NULL,
    value        TEXT NOT NULL,
    PRIMARY KEY(citation_key, type, language)
    );
    """
    )

    c.execute(
    """
    CREATE TABLE dates (
    citation_key TEXT NOT NULL,
    type         TEXT DEFAULT NULL,
    year         INTEGER NOT NULL,
    month        INTEGER DEFAULT NULL,
    day          INTEGER DEFAULT NULL,
    PRIMARY KEY(citation_key, type)
    );
    """
    )

    print( "rkv: initialized {:s}". format( database ) )

def main( argc, argv ):
    database   = DEFAULT_DATABASE
    language   = DEFAULT_LANGUAGE
    pdfviewer  = DEFAULT_PDFVIEWER
    repository = DEFAULT_REPOSITORY

    if ( argc == 1 ):
        print( "rkv: command-line reference manager" )
        print( "database   = {:s}".format( database   ) )
        print( "language   = {:s}".format( language   ) )
        print( "pdfviewer  = {:s}".format( pdfviewer  ) )
        print( "repository = {:s}".format( repository ) )
    elif ( argv[1] == "add" ):
        print( "add" )
    elif ( argv[1] == "init" ):
        init( database )
    elif ( argv[1] == "info" ):
        print( "info" )
    elif ( argv[1] == "list" ):
        print( "list" )
    elif ( argv[1] == "modify" ):
        print( "modify" )
    elif ( argv[1] == "mv" ):
        print( "mv" )
    elif ( argv[1] == "rm" ):
        print( "rm" )
    else:
        print( "rkv: command {:s} is unknown".format( argv[1] ) )

    exit(0)

if __name__ == "__main__":
    main( len(sys.argv), sys.argv )
